name: 1.0.0$(rev:.r)
pool:
  vmImage: 'ubuntu-16.04'
trigger:
- master
steps:
- bash: 'echo "##vso[build.updatebuildnumber]$(Build.BuildNumber)-pr"'
  displayName: 'Set prerelease if not master'
  condition: and(succeeded(), ne(variables['Build.SourceBranch'], 'refs/heads/master'))
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    projects: '**/*.csproj'
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    projects: '**/*.csproj'
    arguments: '-c Release /p:Version=$(Build.BuildNumber)'
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: pack
    configuration: Release
    packDirectory: artifacts
    versioningScheme: byEnvVar
    versionEnvVar: Build_BuildNumber
    nobuild: true
- task: DotNetCoreCLI@2
  displayName: Test
  inputs:
    command: test
    projects: '**/*[Tt]ests/*.csproj'
    arguments: '--configuration Release'
- task: NuGetCommand@2
  displayName: Push
  condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
  inputs:
    command: push
    packagesToPush: 'artifacts/*.nupkg'
    nuGetFeedType: external
    publishFeedCredentials: nuget.org